apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-viewer-binding
subjects:
  - kind: Group
    name: dev-viewer-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dev-viewer
  apiGroup: rbac.authorization.k8s.io
