{
 "title": "teste",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage $instance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\r\n(\r\n  avg(node_memory_MemAvailable_bytes{job=\"observabilidade\",  instance=\"${instance:csv}\"}) /\r\n  avg(node_memory_MemTotal_bytes{job=\"observabilidade\",  instance=\"${instance:csv}\"})\r\n* 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"$cluster\", mode=~\"idle|iowait|steal\", instance=\"${instance:csv}\"}[$__rate_interval])))\r\n/ ignoring(cpu) group_left\r\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"$cluster\", mode=\"idle\", instance=\"${instance:csv}\"})\r\n)\r\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage $instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"$cluster\", instance=\"${instance:csv}\", fstype!=\"\", mountpoint!=\"\"})\r\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"$cluster\", instance=\"${instance:csv}\", fstype!=\"\", mountpoint!=\"\"})\r\n"
    }
   ]
  }
 ]
}