{
 "title": "Custos - Contas",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "var_contas",
    "label": "Contas",
    "query": "SELECT DISTINCT account_name FROM accounts ORDER BY account_name;"
   },
   {
    "name": "var_meses",
    "label": "Meses",
    "query": "SELECT DISTINCT TO_CHAR(date_register, 'YYYY-MM') as month FROM resource_costs ORDER BY month DESC;\n"
   },
   {
    "name": "var_ultimo_mes",
    "query": "SELECT TO_CHAR(MAX(date_register), 'YYYY-MM') as month FROM resource_costs;"
   }
  ]
 },
 "panels": [
  {
   "title": "Contas Analisadas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(account_id) FROM accounts WHERE account_name IN ( $var_contas  )"
    }
   ]
  },
  {
   "title": "Último Scan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(max(date_register), 'DD/MM/YY') FROM accounts WHERE account_name IN ( $var_contas  );"
    }
   ]
  },
  {
   "title": "Top Valor - mês $var_meses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concat(a.account_name, CHR(10), to_char(SUM(ac.unblended_cost), 'US$FM999G999G999D00')) AS display_text, SUM(ac.unblended_cost) AS total_cost, TO_CHAR(ac.date_register, 'Mon-YY') AS month_name\r\nFROM account_costs ac\r\nJOIN accounts a ON ac.account_id = a.account_id\r\nWHERE TO_CHAR(ac.date_register, 'YYYY-MM') = '${var_meses}' AND a.account_name IN ( $var_contas  )\r\nGROUP BY a.account_name,  ac.account_id, TO_CHAR(ac.date_register, 'YYYY-MM'), TO_CHAR(ac.date_register, 'Mon-YY')\r\nORDER BY total_cost DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Distribuição dos custos  no mês $var_meses",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT a.account_profile, ac.unblended_cost AS total_cost\r\nFROM account_costs as ac\r\nJOIN accounts a ON ac.account_id = a.account_id\r\nWHERE TO_CHAR(ac.date_register, 'YYYY-MM') = '${var_meses}' AND a.account_name IN ( $var_contas  )\r\nGROUP BY a.account_profile, ac.unblended_cost\r\nORDER BY total_cost DESC;\r\n"
    }
   ]
  },
  {
   "title": "Custo das Contas NIKE",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select TO_CHAR(date_register, 'YYYY-MM') AS month, TO_CHAR(date_register, 'Mon-YY') AS month_name, sum(unblended_cost) \r\nfrom account_costs \r\ngroup by TO_CHAR(date_register, 'YYYY-MM'), TO_CHAR(date_register, 'Mon-YY') \r\norder by TO_CHAR(date_register, 'YYYY-MM') desc;"
    }
   ]
  },
  {
   "title": "Top Contas dos últimos 3 meses",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH ranked_costs AS (\r\n    SELECT\r\n        a.account_profile,\r\n        TO_CHAR(ac.date_register, 'YYYY-MM') AS month,\r\n        SUM(ac.unblended_cost) AS total_cost,\r\n        DENSE_RANK() OVER (PARTITION BY TO_CHAR(ac.date_register, 'YYYY-MM') ORDER BY SUM(ac.unblended_cost) DESC) AS rank\r\n    FROM\r\n        account_costs ac\r\n    JOIN\r\n        accounts a ON ac.account_id = a.account_id\r\n    GROUP BY\r\n        a.account_profile,\r\n        TO_CHAR(ac.date_register, 'YYYY-MM')\r\n)\r\nSELECT\r\n    month,\r\n    account_profile,\r\n    total_cost\r\nFROM\r\n    ranked_costs\r\nWHERE\r\n    rank <= 3\r\nORDER BY\r\n    month DESC,\r\n    rank\r\nLIMIT 9;\r\n"
    }
   ]
  }
 ]
}