  - job_name: "experian-replication-streaming-producer-s3-as-is"
    ec2_sd_configs:
      - region: sa-east-1
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: 'experian-replication-streaming-producer-s3-as-is'
        action: keep
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
        replacement: '${1}:9100'


  - job_name: "EMR - CREATE CLUSTER - DEV DS"
    ec2_sd_configs:
      - region: sa-east-1
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: 'experian_datahub_multiprovider'
        action: keep
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
        replacement: '${1}:9100'

