apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: monitoring-system
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - "prometheus.uat-ds.br.experian.eeca"
    port:
      name: http
      number: 8080
      protocol: HTTP
