
[[servers]]
host = "10.96.215.13"
port = 389
use_ssl = false
start_tls = false
tls_ciphers = []
min_tls_version = ""
ssl_skip_verify = false
bind_dn = "CN=usr-nikedata-observ,OU=Service Accounts,OU=Accounts,DC=br,DC=experian,DC=local"
bind_password = "GhS#Y8U#hgTY"
search_filter = "(sAMAccountName=%s)"
# An array of base dns to search through
search_base_dns = ["DC=br,DC=experian,DC=local"]
timeout = 10

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "CN=APP-OBSERVABILIDADE-NIKEDATAPROD-USERS,OU=Application Groups,OU=Groups,DC=br,DC=experian,DC=local"
org_role = "Viewer"
[[servers.group_mappings]]
group_dn = "CN=APP-OBSERVABILIDADE-NIKEDATAPROD-ADMINS,OU=Application Groups,OU=Groups,DC=br,DC=experian,DC=local"
org_role = "Admin"
grafana_admin=true
