{
 "title": "Custos - Tags",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "var_contas",
    "label": "Contas",
    "query": "SELECT DISTINCT account_name FROM accounts ORDER BY account_name;"
   },
   {
    "name": "var_servicos",
    "label": "Serviço",
    "query": "SELECT DISTINCT service FROM resource_costs ORDER BY service;"
   },
   {
    "name": "var_meses",
    "label": "Meses",
    "query": "SELECT DISTINCT TO_CHAR(date_register, 'YYYY-MM') as month FROM resource_costs ORDER BY month DESC;\n"
   },
   {
    "name": "var_ultimo_mes",
    "query": "SELECT TO_CHAR(MAX(date_register), 'YYYY-MM') as month FROM resource_costs;"
   },
   {
    "name": "var_tags",
    "label": "Tags Name",
    "query": "SELECT \n    tag_name, \n    SUM(unblended_cost) AS total_cost\nFROM \n    tag_details_costs\nWHERE \n    date_register >= date_trunc('month', current_date - interval '1 month')\n    AND date_register < date_trunc('month', current_date)\nGROUP BY \n    tag_name\nORDER BY \n    total_cost DESC;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Tags Analisadas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(distinct(tdc.tag_name)) \r\nFROM\r\n  tag_details_costs tdc \r\nJOIN\r\n  accounts a ON tdc.account_id = a.account_id\r\nWHERE \r\n  tdc.service IN ( $var_servicos ) AND \r\n  a.account_name IN ( $var_contas )\r\n"
    }
   ]
  },
  {
   "title": "Último Scan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(max(date_register), 'DD/MM/YY') FROM accounts WHERE account_name IN ( $var_contas  );"
    }
   ]
  },
  {
   "title": "Top Valor - mês $var_meses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  concat(tdc.tag_name, CHR(10), to_char(sum(tdc.unblended_cost), 'US$FM999G999G999D00')) as display_text, \r\n  sum(tdc.unblended_cost) as total_cost \r\nFROM \r\n  tag_details_costs tdc\r\nJOIN\r\n  accounts a ON tdc.account_id = a.account_id\r\nWHERE \r\n  TO_CHAR(tdc.date_register, 'YYYY-MM') = '${var_meses}' AND\r\n  tdc.service IN ( $var_servicos ) AND\r\n  a.account_name IN ( $var_contas )\r\nGROUP BY \r\n  tdc.tag_name\r\nORDER BY \r\n  total_cost DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Tags Name no mês $var_meses",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE \r\n      WHEN LENGTH(tdc.tag_name) > 10 THEN\r\n          substring(tdc.tag_name FROM 1 FOR 5) || '...' || substring(tdc.tag_name FROM LENGTH(tdc.tag_name) - 4)\r\n      ELSE\r\n          tdc.tag_name\r\n  END AS short_tag_name,\r\n  SUM(tdc.unblended_cost) AS total_cost\r\nFROM \r\n  tag_details_costs tdc\r\nJOIN\r\n  accounts a ON tdc.account_id = a.account_id\r\nWHERE \r\n  TO_CHAR(tdc.date_register, 'YYYY-MM') = '${var_meses}' \r\n  AND tdc.service IN (${var_servicos})\r\n  AND a.account_name IN ( $var_contas )\r\nGROUP BY \r\n    short_tag_name\r\nORDER BY \r\n    total_cost DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Custo Tag Name $var_tags nos meses",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TO_CHAR(tdc.date_register, 'YYYY-MM') AS month,\r\n  a.account_profile,\r\n  CASE \r\n      WHEN LENGTH(tdc.tag_name) > 10 THEN\r\n          substring(tdc.tag_name FROM 1 FOR 5) || '...' || substring(tdc.tag_name FROM LENGTH(tdc.tag_name) - 4)\r\n      ELSE\r\n          tdc.tag_name\r\n  END AS short_tag_name,\r\n  sum(tdc.unblended_cost) as total_cost\r\nFROM \r\n  tag_details_costs tdc\r\nJOIN \r\n  accounts a ON tdc.account_id = a.account_id\r\nWHERE \r\n  tdc.tag_name = '$var_tags'\r\n  AND tdc.service IN (${var_servicos})\r\n  AND a.account_name IN ($var_contas)\r\nGROUP BY\r\n  TO_CHAR(tdc.date_register, 'YYYY-MM'), \r\n  a.account_profile,\r\n  tdc.tag_name\r\nORDER BY \r\n  TO_CHAR(tdc.date_register, 'YYYY-MM') desc;\r\n"
    }
   ]
  },
  {
   "title": "Top Tags Names dos últimos 3 meses",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH ranked_costs AS (\r\n    SELECT\r\n        tdc.tag_name AS short_tag_name,\r\n        TO_CHAR(tdc.date_register, 'YYYY-MM') AS month,\r\n        SUM(tdc.unblended_cost) AS total_cost,\r\n        DENSE_RANK() OVER (PARTITION BY TO_CHAR(tdc.date_register, 'YYYY-MM') ORDER BY SUM(tdc.unblended_cost) DESC) AS rank\r\n    FROM\r\n      tag_details_costs tdc\r\n    JOIN\r\n      accounts a ON tdc.account_id = a.account_id\r\n    WHERE \r\n      tdc.service IN (${var_servicos})\r\n      AND a.account_name IN ( $var_contas )\r\n    GROUP BY\r\n        tdc.tag_name,\r\n        TO_CHAR(tdc.date_register, 'YYYY-MM')\r\n)\r\nSELECT\r\n    month,\r\n    short_tag_name,\r\n    total_cost\r\nFROM\r\n    ranked_costs\r\nWHERE\r\n    rank <= 5\r\nORDER BY\r\n    month DESC,\r\n    rank\r\nLIMIT 15;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Tags Name no mês $var_meses",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  tdc.tag_name as short_tag_name, SUM(tdc.unblended_cost) AS total_cost\r\nFROM \r\n  tag_details_costs tdc\r\nJOIN\r\n  accounts a ON tdc.account_id = a.account_id\r\nWHERE \r\n  TO_CHAR(tdc.date_register, 'YYYY-MM') = '${var_meses}' \r\n  AND tdc.service IN (${var_servicos})\r\n  AND a.account_name IN ( $var_contas )\r\nGROUP BY \r\n    short_tag_name\r\nORDER BY \r\n    total_cost DESC\r\nLIMIT 10;\r\n"
    }
   ]
  }
 ]
}