{
 "title": "Custos - Serviços",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "var_contas",
    "label": "Contas",
    "query": "SELECT DISTINCT account_name FROM accounts ORDER BY account_name;"
   },
   {
    "name": "var_servicos",
    "label": "Serviço",
    "query": "SELECT DISTINCT service FROM resource_costs ORDER BY service;"
   },
   {
    "name": "var_meses",
    "label": "Meses",
    "query": "SELECT DISTINCT TO_CHAR(date_register, 'YYYY-MM') as month FROM resource_costs ORDER BY month DESC;\n"
   },
   {
    "name": "var_ultimo_mes",
    "query": "SELECT TO_CHAR(MAX(date_register), 'YYYY-MM') as month FROM resource_costs;"
   }
  ]
 },
 "panels": [
  {
   "title": "Serviços Analisados",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(service)) from resource_costs;"
    }
   ]
  },
  {
   "title": "Último Scan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(max(date_register), 'DD/MM/YY') FROM accounts WHERE account_name IN ( $var_contas  );"
    }
   ]
  },
  {
   "title": "Top Valor - mês $var_meses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concat(service, CHR(10), to_char(sum(unblended_cost), 'US$FM999G999G999D00')) as display_text, sum(unblended_cost) as total_cost \r\nFROM resource_costs \r\nWHERE TO_CHAR(date_register, 'YYYY-MM') = '${var_meses}' \r\nGROUP BY service \r\nORDER BY total_cost DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Distribuição dos custos  no mês $var_meses",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT s.short_name, sum(rc.unblended_cost) AS total_cost\r\nFROM resource_costs rc\r\nJOIN servicos s ON rc.service = s.service\r\nWHERE TO_CHAR(rc.date_register, 'YYYY-MM') = '${var_meses}'\r\nGROUP BY s.short_name\r\nORDER BY total_cost DESC;\r\n"
    }
   ]
  },
  {
   "title": "Custo Serviços: $var_servicos",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TO_CHAR(rc.date_register, 'YYYY-MM') AS month,\r\n  TO_CHAR(rc.date_register, 'Mon-YY') AS month_name, \r\n  s.short_name, \r\n  sum(rc.unblended_cost) as total_cost\r\nFROM \r\n  resource_costs rc\r\nJOIN \r\n  accounts a ON rc.account_id = a.account_id\r\nJOIN\r\n  servicos s ON rc.service = s.service\r\nWHERE \r\n  rc.service IN ($var_servicos) \r\n  AND a.account_name IN ($var_contas)\r\nGROUP BY\r\n  TO_CHAR(rc.date_register, 'YYYY-MM'), \r\n  TO_CHAR(rc.date_register, 'Mon-YY'), \r\n  s.short_name\r\nORDER BY \r\n  TO_CHAR(rc.date_register, 'YYYY-MM') desc;\r\n"
    }
   ]
  },
  {
   "title": "Top Serviços dos últimos 3 meses",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH ranked_costs AS (\r\n    SELECT\r\n        s.short_name as service,\r\n        TO_CHAR(rc.date_register, 'YYYY-MM') AS month,\r\n        SUM(rc.unblended_cost) AS total_cost,\r\n        DENSE_RANK() OVER (PARTITION BY TO_CHAR(rc.date_register, 'YYYY-MM') ORDER BY SUM(rc.unblended_cost) DESC) AS rank\r\n    FROM\r\n        resource_costs rc\r\n    JOIN\r\n        servicos s ON rc.service = s.service\r\n    GROUP BY\r\n        s.short_name,\r\n        TO_CHAR(rc.date_register, 'YYYY-MM')\r\n)\r\nSELECT\r\n    month,\r\n    service,\r\n    total_cost\r\nFROM\r\n    ranked_costs\r\nWHERE\r\n    rank <= 6\r\nORDER BY\r\n    month DESC,\r\n    rank\r\nLIMIT 18;\r\n"
    }
   ]
  }
 ]
}