apiVersion: v1
kind: Namespace
metadata:
  name: teste
  labels:
    name: teste
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: teste
  name: my-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teste
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1  # Define o número de réplicas desejadas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: my-service-account
      serviceAccount: my-service-account
      containers:
      - name: nginx
        image: nginx:latest  # Imagem do Docker Hub
        ports:
        - containerPort: 80  # Porta que o contêiner Nginx está escutando
 