# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::087086536124:role/BURoleForAppsEKS
    meta.helm.sh/release-name: ebisys-service-report-analytic-charging-api
    meta.helm.sh/release-namespace: ssbl-dev
  creationTimestamp: "2024-03-28T18:40:04Z"
  labels:
    AppId: "12474"
    CostString: 1800.BR.124.602000
    Environment: dev
    app: ebisys-service-report-analytic-charging-api
    app.kubernetes.io/instance: ebisys-service-report-analytic-charging-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ebisys-service-report-analytic-charging-api
    app.kubernetes.io/version: 1.2.0-SNAPSHOT
    chart: ebisys-service-report-analytic-charging-api-1.2.0-SNAPSHOT
    gearr: "12474"
    helm.sh/chart: ebisys-service-report-analytic-charging-api-1.2.0-SNAPSHOT
    version: 1.2.0-SNAPSHOT
  name: ssbl-dev-perms
  namespace: ssbl-dev
  resourceVersion: "367082428"
  uid: 0cde2c9a-098e-4150-9439-da3199958ead
