okta-aws-cli web --profile bnsprod --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile bnsuat --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile dataofficedev --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile dataofficeuat --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile dataservicesdev --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile dataservicesprod --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile dataservicesstage --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile positivoprod --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile positivouat --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile datahubdev --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile datahubprod --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile datahubstage --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile sremanagementdev --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile nikedataservicedev --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile nikedataserviceprod --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile nikedataserviceuat --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile architecturesandbox --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile corporatedev --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile corporateprod --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile bnspssrmprodrod --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile ssrmsandbox --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile ssrmdev --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile negativodev --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile negativosandbox --aws-region sa-east-1 --aws-session-duration 36000
okta-aws-cli web --profile positivodev --aws-region sa-east-1 --aws-session-duration 36000
